/**
 * PrivacyIndicator component for displaying privacy status.
 *
 * Shows whether a response came from local (private) or cloud (anonymized)
 * backend. Provides transparency about data handling for privacy-conscious users.
 */

import { useState } from 'react';
import { cn } from '@/lib/utils';

/**
 * Shield icon for local/private indicator.
 */
function ShieldIcon({ className }: { className?: string }) {
  return (
    <svg
      className={cn('w-3 h-3', className)}
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"
      />
    </svg>
  );
}

/**
 * Cloud icon for cloud/anonymized indicator.
 */
function CloudIcon({ className }: { className?: string }) {
  return (
    <svg
      className={cn('w-3 h-3', className)}
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z"
      />
    </svg>
  );
}

export interface PrivacyIndicatorProps {
  /** Which backend processed the request */
  backend: 'local' | 'cloud';
  /** List of fields that were anonymized (for cloud requests) */
  anonymizedFields?: string[];
  /** Additional CSS classes */
  className?: string;
}

/**
 * PrivacyIndicator displays the privacy status of a response.
 *
 * - Local: Green shield with "Private" - data stays on device
 * - Cloud: Blue cloud with "Anonymized" - data was scrubbed before transmission
 *
 * Hovering reveals details about what was anonymized (cloud only).
 *
 * @example
 * ```tsx
 * <PrivacyIndicator backend="local" />
 * <PrivacyIndicator
 *   backend="cloud"
 *   anonymizedFields={['path: username anonymized', 'ip: IP address anonymized']}
 * />
 * ```
 */
function PrivacyIndicator({
  backend,
  anonymizedFields = [],
  className,
}: PrivacyIndicatorProps) {
  const [showTooltip, setShowTooltip] = useState(false);

  const isLocal = backend === 'local';

  return (
    <div className={cn('relative inline-flex', className)}>
      <button
        type="button"
        className={cn(
          'inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium',
          'transition-colors duration-150',
          isLocal
            ? 'bg-success/10 text-success hover:bg-success/20'
            : 'bg-primary/10 text-primary hover:bg-primary/20'
        )}
        onMouseEnter={() => setShowTooltip(true)}
        onMouseLeave={() => setShowTooltip(false)}
        onFocus={() => setShowTooltip(true)}
        onBlur={() => setShowTooltip(false)}
        aria-label={isLocal ? 'Private: Data stayed on device' : 'Anonymized: Data was scrubbed before cloud transmission'}
      >
        {isLocal ? (
          <>
            <ShieldIcon className="w-2.5 h-2.5" />
            <span>Private</span>
          </>
        ) : (
          <>
            <CloudIcon className="w-2.5 h-2.5" />
            <span>Anonymized</span>
          </>
        )}
      </button>

      {/* Tooltip */}
      {showTooltip && (
        <div
          className={cn(
            'absolute z-50 bottom-full left-0 mb-1.5',
            'w-64 p-2 rounded-lg shadow-lg',
            'bg-popover border border-border text-popover-foreground',
            'text-xs'
          )}
          role="tooltip"
        >
          {isLocal ? (
            <div>
              <div className="font-medium text-success mb-1">Data Stays Private</div>
              <p className="text-muted-foreground">
                This response was generated by a local AI model. Your system data never left your device.
              </p>
            </div>
          ) : (
            <div>
              <div className="font-medium text-primary mb-1">Anonymized for Cloud</div>
              <p className="text-muted-foreground mb-2">
                Your data was scrubbed before being sent to Claude. Personal identifiers were removed.
              </p>
              {anonymizedFields.length > 0 && (
                <div>
                  <div className="text-[10px] font-medium text-muted-foreground uppercase tracking-wider mb-1">
                    What was anonymized:
                  </div>
                  <ul className="space-y-0.5">
                    {anonymizedFields.map((field, index) => (
                      <li
                        key={index}
                        className="text-muted-foreground flex items-start gap-1"
                      >
                        <span className="text-primary">-</span>
                        <span>{field}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              {anonymizedFields.length === 0 && (
                <p className="text-muted-foreground italic">
                  No sensitive data was detected in this request.
                </p>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default PrivacyIndicator;
