name: OptaLMiOS
options:
  bundleIdPrefix: com.opta
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  developmentLanguage: en
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"

configFiles:
  Debug: GoogleService.xcconfig
  Release: GoogleService.xcconfig

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_PREVIEWS: YES
    GENERATE_INFOPLIST_FILE: NO
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    DEVELOPMENT_TEAM: "77PKS547H5"
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_FILE: OptaLMiOS/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.opta.lm.ios
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      SWIFT_OPTIMIZATION_LEVEL: "-O"

targets:
  OptaLMiOS:
    type: application
    platform: iOS
    sources:
      - path: OptaLMiOS
        excludes:
          - "*.entitlements"
    settings:
      base:
        PRODUCT_NAME: "Opta LM"
        INFOPLIST_FILE: OptaLMiOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.opta.lm.ios
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
    dependencies:
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift

schemes:
  OptaLMiOS:
    build:
      targets:
        OptaLMiOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
