/* eslint-disable */
// Auto-generated by scripts/generate-release-notes.mjs
// Generated at: 2026-03-01T16:52:03.606Z

import type { ReleaseNote } from './release-notes'

export const GENERATED_RELEASE_NOTES: ReleaseNote[] = [
  {
    "id": "2026-02-26-model-runtime-1",
    "date": "2026-02-26",
    "title": "Model Runtime Activity",
    "summary": "9 model lifecycle events were recorded for the LMX runtime.",
    "status": "released",
    "highlights": [
      "Loads: 9 · Unloads: 0",
      "Models touched: mlx-community/MiniMax-M2.5-4bit, inferencerlabs/MiniMax-M2.5-MLX-6.5bit",
      "Source: Opta LMX update logs"
    ],
    "links": [
      {
        "label": "LMX Features",
        "href": "/features?app=lmx"
      }
    ]
  },
  {
    "id": "2026-02-26-stack-sync-2",
    "date": "2026-02-26",
    "title": "Stack Sync & Promotion Updates",
    "summary": "6 stack sync runs recorded across CLI/LMX components.",
    "status": "released",
    "highlights": [
      "Modes: auto, remote, both",
      "opta update (auto) — cli, lmx, plus",
      "opta update (remote) — cli, lmx, plus",
      "Source: Opta CLI update logs"
    ],
    "links": [
      {
        "label": "CLI Features",
        "href": "/features?app=cli"
      }
    ]
  },
  {
    "id": "2026-02-25-model-runtime-3",
    "date": "2026-02-25",
    "title": "Model Runtime Activity",
    "summary": "3 model lifecycle events were recorded for the LMX runtime.",
    "status": "released",
    "highlights": [
      "Loads: 3 · Unloads: 0",
      "Models touched: inferencerlabs/MiniMax-M2.5-MLX-6.5bit",
      "Source: Opta LMX update logs"
    ],
    "links": [
      {
        "label": "LMX Features",
        "href": "/features?app=lmx"
      }
    ]
  },
  {
    "id": "2026-02-24-model-runtime-4",
    "date": "2026-02-24",
    "title": "Model Runtime Activity",
    "summary": "6 model lifecycle events were recorded for the LMX runtime.",
    "status": "released",
    "highlights": [
      "Loads: 6 · Unloads: 0",
      "Models touched: inferencerlabs/MiniMax-M2.5-MLX-6.5bit, mlx-community/MiniMax-M2.5-4bit, inferencerlabs/GLM-5-MLX-4.8bit",
      "Source: Opta LMX update logs"
    ],
    "links": [
      {
        "label": "LMX Features",
        "href": "/features?app=lmx"
      }
    ]
  },
  {
    "id": "2026-02-23-stack-sync-5",
    "date": "2026-02-23",
    "title": "Stack Sync & Promotion Updates",
    "summary": "11 stack sync runs recorded across CLI/LMX components.",
    "status": "released",
    "highlights": [
      "Modes: auto, remote",
      "opta update (auto) — cli, lmx, plus",
      "opta update (remote) — cli, lmx, plus",
      "Source: Opta CLI update logs"
    ],
    "links": [
      {
        "label": "CLI Features",
        "href": "/features?app=cli"
      }
    ]
  }
]
