name: OptaLocal
options:
  bundleIdPrefix: com.opta
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "5.9"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  OptaLocal:
    type: application
    platform: iOS
    sources:
      - OptaLocal
    info:
      path: OptaLocal/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.opta.local
        INFOPLIST_FILE: OptaLocal/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
